controller:
  service:
    type: LoadBalancer
    annotations:
        # List of annotations available:
        # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/service/annotations/
        # Use NLB(Network Load Balancer)
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
        # If proxy-protocol is not enabled in NLB, it causes 'broken header' error in nginx
        # If newly created NLB does not be created with proxy protocol configuration
        # Change it manually: EC2 > Load Balancing > Target Group > Edit > 'Enable proxy protocol v2'
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    config:
      # This is required to client's IP-based access control (This config allows nlb passes a original client ip to nginx)
      use-proxy-protocol: true
