apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    test: nginx-2
  name: nginx-2
  namespace: test
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 30321
